### PR TITLE
Update to latest kuberesolver

### PR DESCRIPTION
**Pull request by gouthamve**
@tomwilkie @bboreham

### CODE REVIEW

**Comment by gouthamve** [comment]
Nope, but it uses the new gRPC API for loadblancing. It's just the updated version of the previous library.

**Comment by bboreham** [comment]
Review might go faster if you say what is going on in the 80-odd lines of changes.

**Comment by gouthamve** [comment]
Previously, we needed to pass in a resolver as an option. And the resolver used to do both resolution and loadbalancing, afaik.

Now, the API changed to "registering" resolvers. i.e, mapping scheme to resolvers, for example `kubernetes://` --> kuberesolver, `dns://` --> dns resolver, etc. And then specifying the load-balancing policy via the resolution mechanism or manually or via an `grpclb`, etc.

See: https://github.com/grpc/proposal/blob/master/L9-go-resolver-balancer-API.md

In this PR, I modified our client creation to use the new API through kuberesolver v2. It was fairly straightforward, needed to remove the additional resolver dial option and needed to specify the loadbalancing.

**Comment by tomwilkie** [comment]
I was also hoping that kuberesolver v2 would fix https://github.com/sercand/kuberesolver/issues/4, but it doesn't appear to.

**Comment by bboreham** [comment]
> for example kubernetes:// --> kuberesolver, dns:// --> dns resolver, etc. 

According to https://github.com/grpc/grpc-go/blob/v1.19.0/clientconn.go#L125 those should have three slashes.  Did you test this code?

**Comment by gouthamve** [comment]
Oh right, we ended up using `dns:///` which worked. Though let me update the code to make it `:///`

**Pull request merged**
