### PR TITLE
Add flag to log requests at info level

### PR DESCRIPTION
**Pull request by colin-stuart**
Adds an optional flag to log requests at the info level, still defaulting to logging requests at the debug level.

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks for the PR. 

It’s now calling `logWithRequest` about six times; can you factor that out?

**Comment by colin-stuart** [comment]
Thanks for the the review @bboreham, let me know what you think about the refactor. Another option would be to add another global convenience function that takes a `level` string and a calls the appropriate `Debugf()`/`Infof()`/etc. function.

**Comment by bboreham** [comment]
What I meant was: call `logWithRequest` once, then hold the resulting `logging.Interface` in a variable for the duration of the `Wrap()` inner function.
It's a relatively expensive operation: https://github.com/weaveworks/common/blob/933588f9873757f6db44841b0919ddaa8c207f98/middleware/logging.go#L23-L38

**Comment by colin-stuart** [comment]
Thanks @bboreham, I see what you meant now!

**Comment by bboreham** [comment]
Looks better now, thanks.  Have you tried it?

**Comment by colin-stuart** [comment]
Yep, enabled it for a service running locally and the requests logs are showing at the info level.

**Pull request merged**
