### PR TITLE
Allow the AWS backend to get credentials from its environment.

### PR DESCRIPTION
**Pull request by tomwilkie**
See https://github.com/weaveworks/cortex/pull/898

Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

### CODE REVIEW

**Comment by bboreham** [comment]
What is the failure mode now if you forget to supply credentials via parameter or environment?

**Comment by tomwilkie** [comment]
Assuming there are no credentials in the environment it'll still fail on startup, with something along the lines of "No credentials in chain".

If you run it on AWS through, there are always some credentials available - they just might not allow you to read or write from dynamodb.  In this case the individual reads & writes will fail.

**Comment by tomwilkie** [comment]
ping @bboreham?

**Comment by bboreham** [comment]
I was trying to get more feedback from users of this library.

**Comment by bboreham** [comment]
Thanks @tomwilkie !

**Pull request merged**
